### ISSUE TITLE
[Feature request] Bundle XDelta with the AppImage

### ISSUE THREAD

**Issue by Twig6943** [dan0v/xdelta3-cross-gui#42]
title. 
(Not sure if this is a thing but doesn't seem to be.)

![image](https://github.com/user-attachments/assets/3aca2b91-ed99-4d47-9216-84aeffd79f70)

**Comment by Twig6943** [comment]
This app has xdelta bundled https://flathub.org/apps/io.github.marco_calautti.DeltaPatcher

**Comment by dan0v** [comment]
xDelta is also included inside the AppImage. If you have separately installed xDelta to your system and the app detects it on your system path, that version will be used for creating patches instead of the one included with the app. If you have the "Copy xDelta executables to output directory" option selected, the Windows, Mac, and Linux binaries copied across are the ones which are included inside the app and used for patch creation when xDelta is not detected on the system path.
